### ISSUE TITLE
Window.requestAnimationFrame() polyfill not mentioned in the README

### ISSUE THREAD

**Issue by jaydenseric** [WebReflection/dom4#22]
`Window.requestAnimationFrame()` polyfill is not mentioned in the README, does this mean it is not supported or tested?

**Comment by WebReflection** [comment]
Now tested, I just forgot. I also added a comment in the README. The only caveat is that I don't slow down legacy browsers with the timer logic that is not accurate anyway.

I also don't polyfill such timer logic in archaic versions  because to feature detect that I need an asynchronous execution which will make things a bit more complicated.
