### ISSUE TITLE
requestAnimationFrame callback not passing time in IE9

### ISSUE THREAD

**Issue by loic-h** [WebReflection/dom4#27]
The requestAnimationFrame pass no value in its callback under IE9.
Tested on IE11 with IE9 emulated on a Windows 10 Home system.

Example: https://jsfiddle.net/qrhym5w3/

**Comment by WebReflection** [comment]
There are two problems here:

  * the `rAF` used in here is [a partial polyfill](https://github.com/WebReflection/dom4/blob/master/src/dom4.js#L406) and it won't probably change since the amount of extra code to fully polyfill it is huge and also not 100% reliable anyway due  `Date` inaccuracy, so the effort is kinda not worth the gain. This is [also specified in the README](https://github.com/WebReflection/dom4#features)
  * you are not normalizing timers in IE9 which will bite you with many more libraries.

For the second point, I suggest you to fix every single HTML template file you have adding the following in the header and before any other script.

Don't worry, every other browser will simply ignore that script, considering it a comment.

```html
<!--[if lte IE 9]>
  <script>(function(f){window.setTimeout=f(window.setTimeout);window.setInterval=f(window.setInterval)})(function(f){return function(c,t){var a=[].slice.call(arguments,2);return f(function(){c.apply(this,a)},t)}});</script>
  <![endif]-->
```

This has been [described in this post of mine](https://www.webreflection.co.uk/blog/2015/07/31/the-web-bare-necessities#adding-graceful-enhancement) and it has been used in production since about ever and it's side-effects free.

Once you've added above normalization, you'll receive a `15` as milliseconds values which is already passed, so this is not a real bug.

Best Regards
