### ISSUE TITLE
Will query and queryAll stay in the dom4 polyfill?

### ISSUE THREAD

**Issue by anandgraves** [WebReflection/dom4#31]
According to issue #30, **query** and **queryAll** have been removed from the spec.
Will they stay in the dom4 polyfill or will it reflect the spec and will they be removed at some point?

**Comment by WebReflection** [comment]
I don't know how many developers are using these methods, and it doesn't seem that removing them will give anyone anything, so a major version bump just for that doesn't seem to be worth, IMO.

Are those two methods disturbing you in some particular way?

**Comment by anandgraves** [comment]
On the contrary, I would very much like to keep them in the Dom4 polyfill.

**Comment by WebReflection** [comment]
I don't think I'm going to remove those utilities any time soon but if I do, it'll be a major breaking change so, same ver and code happily ever after ;-)

**Comment by aFarkas** [comment]
While I don't have a strong opinion here. I think these should be removed, because they are not part of a polyfill and should be added as utility methods in a separate DOM lib.

**Comment by WebReflection** [comment]
yeah, it will be removed but a major bump version only for that ain't happening.

It's flagged as deprecated now, might actually bump a patch and add the console.warn for those methods before the bump.

There's no need to break anything

**Comment by ryuran** [comment]
Ok, I wait for next major version.
Because I don’t want useless and non standard code modyfing DOM in prod. 😢

**Comment by WebReflection** [comment]
Big issue, huh? 🤷‍♂️

Tell me about the risks

**Comment by ryuran** [comment]
1. Modifying prototype of DOM object is bad, cf. these articles:
    http://perfectionkills.com/whats-wrong-with-extending-the-dom/
    https://www.nczonline.net/blog/2010/03/02/maintainable-javascript-dont-modify-objects-you-down-own/
    I can accept it for polyfill to resolve future standard.

2 - Dead code in prod. Heavier js without benefit.
      The ideal case is requiring only used polyfill in my project

3 - My developers risk to use this deprecated functions…

**Comment by WebReflection** [comment]
Nothing in those articles applies here, the methods were already defined by specs and then deprecated so:

  * no risks for collisions, W3C doomed these two methods already, these won't be reused later on
  * extending the prototype is what this polyfill does all over. There's zero extra cost in having two extra methods
  * there is no death code because there are developers that use these methods. The current CDN is not used by you or your team, is used by many others and guess what, nobody ever had an issue.
  * the amount of JS you are saving is [this one](https://github.com/WebReflection/dom4/blob/master/src/dom4.js#L134-L164), which is 288 bytes gzipped. If 288 bytes is the problem of your Web site I think you should consider not using JS at all.

No developer risk to do anything. You have code reviews, you write tests, and you either know aboout these methods and the fact these do not exist anymore, or you read the README and you know these methods are deprecated.

Moreover, it looks like you didn't read the linked discussion so if all you can do to contribute is writing this:

> Ok, I wait for next major version.
> Because I don’t want useless and non standard code modyfing DOM in prod. :cry:

all I can say is: _works for me, have a nice day_

**Comment by WebReflection** [comment]
FYI query and queryAll have been removed from v2
