### ISSUE TITLE
`:scope` querySelector breaks on vendor specific selectors [IE11]

### ISSUE THREAD

**Issue by aaarichter** [WebReflection/dom4#49]
In Dom4 v2.1.3 and IE11
A selector like `"input:-webkit-autofill, textarea:-webkit-autofill"` will cause a syntax error in https://github.com/WebReflection/dom4/blob/master/src/dom4.js#L725-L732 

This is a similar issue to #42

**Comment by WebReflection** [comment]
Why are you selecting those in IE11 since it'll never produce anything?
The only fix is a try catch around that always returns an empty result, slowing down every other normal selector, not sure that's what all others dom4 users would like though, at the end any browser could throw with unsupported selectors so this is more like a won't fix.

**Comment by aaarichter** [comment]
@WebReflection I have code like `if (parentNode.querySelector('input:-webkit-autofill'))` to test for the autocomplete feature. This triggers the code in the code line mentioned above.

I guess I have to test for the browser (chrome / safari) in the condition first to avoid DOM4 querySelector for this specific selector

**Comment by WebReflection** [comment]
Are you saying without dom4 those selectors work on IE?

**Comment by WebReflection** [comment]
Anyway, till Monday
https://offline.report/?user=webreflection

**Comment by aaarichter** [comment]
> Are you saying without dom4 those selectors work on IE? 

No, not saying this. It fails with a syntax error as well.
Maybe it is possible to test for vendor pseudo selector and return an empty nodelist in this case.

**Comment by WebReflection** [comment]
I've flagged this as invalid because the title has not much to do with the issue but I am also tagging this as won't fix because I have no intention to allow any sort of selector to work in IE, it's out of this module scope.

If you use vendors specific selectors either don't use qSA in other vendors or use a try catch around.

Slowing all valid use cases since 2015 because of some code trashing webkit stuff into IE11 looks too much of a stretch here.
