### ISSUE TITLE
`once` is not an option for `removeEventListener`

### ISSUE THREAD

**Issue by roydukkey** [WebReflection/dom4#53]
https://github.com/WebReflection/dom4/blob/1fec339bec701430287fc41a34d480998e6b4a47/src/event-target.js#L133

Is there a specific reason `once` was added to `rEL` for the feature test? The [docs on MDN](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener#parameters) don't list this as a valid option.

I would expect the line to be rewritten as `rEL('_', increment);`, since there might be other browsers that will actually throw an error at this point, even though `aEL('_', increment, { once: true });` functions properly.

**Comment by WebReflection** [comment]
no browser will throw an error ever, they eventually ignore the third argument. on the other side, if you added/removed a listener via `true` or `false`, how do you know which of the two you should remove?

here I am just using a symmetric signature, and it worked well from IE8+, and this module is *old*, changing this might, instead, cause issues, while keeping it won't throw ever (because new browsers don't get patched while old browsers never threw a thing).
